apiVersion: external-secrets.io/v1beta1

kind: ExternalSecret

metadata:

  name: db-secret

spec:

  refreshInterval: 1h

  secretStoreRef:

    name: aws-secrets-manager

    kind: ClusterSecretStore

  target:

    name: db-secret

  data:

  - secretKey: password

    remoteRef:

      key: platform/db-password

      property: password